[project]
name = "gexray"
version = "2025.3.17"
description = "Visualizing Gex and other options data real-time."
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["trade_tempo", "bin/gex_to_db_dev"]
