services:
  inferred_gex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inferred_gex
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_REMOTE=${REDIS_REMOTE:-localhost}
    volumes:
      - ./logs:/app/logs
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
