version: '3.8'

services:
  inferred_gex_processor:
    build: .
    container_name: inferred_gex_processor
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
    restart: unless-stopped
    networks:
      - gexreader_network
    depends_on:
      - postgres
      - redis

  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gexreader_network
    profiles:
      - local

  redis:
    image: redis:7-alpine
    networks:
      - gexreader_network
    profiles:
      - local

volumes:
  postgres_data:

networks:
  gexreader_network:
    external: true