services:
  gexreader3:  # Renamed from 'services' to 'gexray3' for clarity
    build:
      context: .
      dockerfile: Dockerfile
    image: gexrayreader3:v1.0.0
    container_name: gexrayreader3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_REMOTE=${REDIS_REMOTE:-localhost}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - ./logs:/app/logs
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - logs/
        - action: rebuild
          path: ./pyproject.toml